---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
<% %w(12.6.0 latest).each do |chef_version| %>
   - name: ubuntu-12.04-pristine-<%= chef_version %>
     driver_config:
       box: opscode-ubuntu-12.04
       box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-12.04_chef-provisionerless.box
       require_chef_omnibus: <%= chef_version %>
       provision: true
 <% end %>

suites:
  - name: default
    run_list:
      - recipe[unwind_example::default]
