name 'unwind_example'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Tests resource notification'
long_description 'Tests resource notification'
version '0.1.0'
